{ pkgs, ... }:
[
  pkgs.xfce.thunar
  pkgs.xfce.tumbler
  pkgs.pix
  pkgs.killall
  pkgs.jetbrains.jdk
  pkgs.jetbrains.rust-rover
  pkgs.jetbrains.pycharm-professional
  pkgs.jetbrains.clion
  pkgs.jetbrains.idea-ultimate
  pkgs.pavucontrol
  pkgs.font-awesome
  pkgs.nerd-fonts.dejavu-sans-mono
  pkgs.stremio
  pkgs.unrar
  pkgs.unzip
  pkgs.p7zip
]
