{ pkgs, ... }:
[
  pkgs.tumbler
  pkgs.ristretto
  pkgs.killall
  pkgs.jetbrains.jdk
  pkgs.jetbrains.rust-rover
  pkgs.jetbrains.pycharm
  pkgs.jetbrains.clion
  pkgs.jetbrains.idea
  pkgs.pavucontrol
  pkgs.font-awesome
  pkgs.nerd-fonts.dejavu-sans-mono
  pkgs.unrar
  pkgs.unzip
  pkgs.p7zip
  pkgs.thunderbird
  pkgs.legendary-gl
]
